version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "Dependabot 🤖"
    versioning-strategy: "increase"
