retry_wait_time = 3
max_retries = 6
timeout = 120
verbose = "warn"
no_progress = true
exclude_path = ["^var/", "^vendor/", "^\\.git/"]

[hosts."docs.github.com"]
headers = { Accept-Encoding = "zstd, br, gzip, deflate" }
